version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/workspace

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install firebase
          command: sudo npm install -g firebase-bolt
      - run:
          name: Build Rule
          command: firebase-bolt database.rules.bolt

      - restore_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
      - run:
          name: Install packages of functions
          command: cd functions && yarn install && cd ..
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
          paths:
            - functions/node_modules

      - restore_cache:
          key: dependency-cache-{{ checksum "hosting/package.json" }}
      - run:
          name: Install packages of hosting
          command: cd hosting && yarn install && cd ..
      - save_cache:
          key: dependency-cache-{{ checksum "hosting/package.json" }}
          paths:
            - hosting/node_modules
      - run:
          name: Build WebApp
          command: cd hosting && yarn build && cd ..
      
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install firebase
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy to firebase
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
